#ifndef opacity_sdk_h
#define opacity_sdk_h

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

#ifdef __cplusplus
namespace opacity_core {
#endif  // __cplusplus

typedef struct OurExtensionType OurExtensionType;

typedef void (*IosPrepareRequestFn)(const char*);

typedef void (*IosSetRequestHeaderFn)(const char*, const char*);

typedef void (*IosSetCookieFn)(const char*, const char*);

typedef void (*IosPresentWebviewFn)(bool);

typedef void (*IosCloseWebviewFn)(void);

typedef const char *(*IosGetBrowserCookiesForCurrentUrlFn)(void);

typedef const char *(*IosGetBrowserCookiesForDomainFn)(const char*);

typedef const char *(*GetIpAddressFn)(void);

typedef double (*GetBatteryLevelFn)(void);

typedef const char *(*GetBatteryStatusFn)(void);

typedef const char *(*GetCarrierNameFn)(void);

typedef const char *(*GetCarrierMccFn)(void);

typedef const char *(*GetCarrierMncFn)(void);

typedef double (*GetCourseFn)(void);

typedef const char *(*GetCpuAbiFn)(void);

typedef double (*GetAltitudeFn)(void);

typedef double (*GetLatitudeFn)(void);

typedef double (*GetLongitudeFn)(void);

typedef const char *(*GetDeviceModelFn)(void);

typedef const char *(*GetOsNameFn)(void);

typedef const char *(*GetOsVersionFn)(void);

typedef bool (*IsEmulatorFn)(void);

typedef double (*GetHorizontalAccuracyFn)(void);

typedef double (*GetVerticalAccuracyFn)(void);

typedef bool (*IsLocationServicesEnabledFn)(void);

typedef bool (*IsWifiConnectedFn)(void);

typedef bool (*IsRootedFn)(void);

typedef bool (*IsAppForeground)(void);

typedef const char *(*GetDeviceLocaleFn)(void);

typedef int32_t (*GetScreenWidthFn)(void);

typedef int32_t (*GetScreenHeightFn)(void);

typedef float (*GetScreenDensityFn)(void);

typedef int32_t (*GetScreenDpiFn)(void);

typedef const char *(*GetDeviceCpuFn)(void);

typedef const char *(*GetDeviceCodenameFn)(void);

typedef void (*IosWebviewChangeUrlFn)(const char*);

typedef const char *(*IosEvalJsFn)(const char*, double);





























































#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

extern const int32_t OPACITY_OK;

extern const int32_t OPACITY_MISSING_POINTER;

extern const int32_t OPACITY_GENERIC_ERROR;

extern const int32_t OPACITY_NOT_SUPPORTED;

extern const int32_t OPACITY_INVALID_ENVIRONMENT;

extern const int32_t OPACITY_ENVIRONMENT_LOCAL;

extern const int32_t OPACITY_ENVIRONMENT_SANDBOX;

extern const int32_t OPACITY_ENVIRONMENT_STAGING;

extern const int32_t OPACITY_ENVIRONMENT_PRODUCTION;

int32_t opacity_init(const char *api_key_str,
                     bool dry_run,
                     int32_t backend_environment,
                     bool show_errors_in_webview,
                     char **error_ptr);

int32_t opacity_get(const char *name, const char *params, char **res_ptr, char **err_ptr);

/**
 * Like [`opacity_get`], but joins the caller's W3C trace: the flow's root span
 * is parented to the supplied `traceparent`. `tracestate` is optional
 */
int32_t opacity_get_with_context(const char *name,
                                 const char *params,
                                 const char *traceparent,
                                 const char *tracestate,
                                 char **res_ptr,
                                 char **err_ptr);

void opacity_free_string(char *ptr);

void emit_webview_event(const char *payload);

bool is_browser_overlay_enabled(void);

const char *get_browser_overlay_pages_json(void);

const char *get_browser_overlay_observer_script(void);

const char *get_browser_overlay_bootstrap_script(void);

const char *get_browser_overlay_renderer_script(void);

bool is_browser_debug_logs_enabled(void);

const char *get_api_version(void);

int32_t opacity_initialize_open_telemetry(const char *open_telemetry_endpoint,
                                          const char *grafana_instance_id,
                                          const char *grafana_api_token,
                                          char **err_ptr);

extern bool android_is_app_foregrounded(void);

extern const char *android_get_os_version(void);

extern const char *android_get_device_manufacturer(void);

extern const char *android_get_device_model(void);

extern const char *android_get_device_locale(void);

extern int32_t android_get_screen_width(void);

extern int32_t android_get_screen_height(void);

extern float android_get_screen_density(void);

extern int32_t android_get_screen_dpi(void);

extern int32_t android_get_sdk_version(void);

extern const char *android_get_device_cpu(void);

extern const char *android_get_device_codename(void);

extern const char *android_get_bootloader(void);

extern const char *android_get_radio(void);

extern const char *android_get_build_time(void);

extern const char *get_ip_address(void);

void register_ios_callbacks(IosPrepareRequestFn ios_prepare_request,
                            IosSetRequestHeaderFn ios_set_request_header,
                            IosSetCookieFn ios_set_cookie,
                            IosPresentWebviewFn ios_present_webview,
                            IosCloseWebviewFn ios_close_webview,
                            IosGetBrowserCookiesForCurrentUrlFn ios_get_browser_cookies_for_current_url,
                            IosGetBrowserCookiesForDomainFn ios_get_browser_cookies_for_domain,
                            GetIpAddressFn get_ip_address,
                            GetBatteryLevelFn get_battery_level,
                            GetBatteryStatusFn get_battery_status,
                            GetCarrierNameFn get_carrier_name,
                            GetCarrierMccFn get_carrier_mcc,
                            GetCarrierMncFn get_carrier_mnc,
                            GetCourseFn get_course,
                            GetCpuAbiFn get_cpu_abi,
                            GetAltitudeFn get_altitude,
                            GetLatitudeFn get_latitude,
                            GetLongitudeFn get_longitude,
                            GetDeviceModelFn get_device_model,
                            GetOsNameFn get_os_name,
                            GetOsVersionFn get_os_version,
                            IsEmulatorFn is_emulator,
                            GetHorizontalAccuracyFn get_horizontal_accuracy,
                            GetVerticalAccuracyFn get_vertical_accuracy,
                            IsLocationServicesEnabledFn is_location_services_enabled,
                            IsWifiConnectedFn is_wifi_connected,
                            IsRootedFn is_rooted,
                            IsAppForeground is_app_foreground,
                            GetDeviceLocaleFn get_device_locale,
                            GetScreenWidthFn get_screen_width,
                            GetScreenHeightFn get_screen_height,
                            GetScreenDensityFn get_screen_density,
                            GetScreenDpiFn get_screen_dpi,
                            GetDeviceCpuFn get_device_cpu,
                            GetDeviceCodenameFn get_device_codename,
                            IosWebviewChangeUrlFn ios_webview_change_url,
                            IosEvalJsFn ios_eval_js);

extern void secure_set(const char *key, const char *value);

extern const char *secure_get(const char *key);

extern void android_prepare_request(const char *url);

extern void android_set_request_header(const char *key, const char *value);

extern void android_set_cookie(const char *url, const char *value);

extern void android_present_webview(bool should_intercept);

extern void android_close_webview(void);

extern const char *android_get_browser_cookies_for_current_url(void);

extern const char *android_get_browser_cookies_for_domain(const char *domain);

extern void android_webview_change_url(const char *url);

extern const char *android_eval_js(const char *js, double timeout_in_seconds);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#ifdef __cplusplus
}  // namespace opacity_core
#endif  // __cplusplus

#endif  /* opacity_sdk_h */
