name: Release

on:
  push:
    tags:
      - '*'

permissions:
  contents: write
  id-token: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup

      - name: Fix permissions on cli
        run: |
          chmod u+x node_modules/@react-native-community/cli/build/*.js
          chmod u+x node_modules/.bin/rnc-cli

      - name: Update package.json version
        run: |
          TAG_NAME=${GITHUB_REF#refs/tags/}
          jq --arg version "$TAG_NAME" '.version = $version' package.json > tmp.$$.json && mv tmp.$$.json package.json

      - uses: JS-DevTools/npm-publish@v3
        with:
          token: ${{ secrets.NODE_AUTH_TOKEN }}

      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
